create table if not exists public.dog_breeds (
  id text primary key,
  name_ko text not null,
  name_en text not null,
  group_name text,
  aliases text[] not null default '{}',
  is_popular boolean not null default false,
  source text not null default 'manual',
  sort_order integer not null default 1000,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dog_breeds_name_ko_idx on public.dog_breeds (name_ko);
create index if not exists dog_breeds_name_en_idx on public.dog_breeds (name_en);
create index if not exists dog_breeds_aliases_gin_idx on public.dog_breeds using gin (aliases);

alter table public.dog_breeds enable row level security;

drop policy if exists "Dog breeds are publicly readable" on public.dog_breeds;
create policy "Dog breeds are publicly readable"
  on public.dog_breeds for select
  using (true);

insert into public.dog_breeds (
  id,
  name_ko,
  name_en,
  group_name,
  aliases,
  is_popular,
  source,
  sort_order
)
values
('golden-retriever', '골든 리트리버', 'Golden Retriever', 'Sporting Group', array['golden-retriever', 'Golden Retriever', '골든 리트리버']::text[], true, 'akc', 26),
('dachshund', '닥스훈트', 'Dachshund', 'Hound Group', array['dachshund', 'Dachshund', '닥스훈트']::text[], true, 'akc', 56),
('labrador-retriever', '래브라도 리트리버', 'Labrador Retriever', 'Sporting Group', array['labrador-retriever', 'Labrador Retriever', '래브라도 리트리버']::text[], true, 'akc', 31),
('maltese', '말티즈', 'Maltese', 'Toy Group', array['maltese', 'Maltese', '말티즈']::text[], true, 'akc', 150),
('miniature-schnauzer', '미니어처 슈나우저', 'Miniature Schnauzer', 'Terrier Group', array['miniature-schnauzer', 'Miniature Schnauzer', '미니어처 슈나우저']::text[], true, 'akc', 124),
('mixed', '믹스견', 'Mixed Breed', 'Mixed', array['mixed', 'mixed breed', '믹스견', '혼종']::text[], true, 'meoksa', 0),
('border-collie', '보더콜리', 'Border Collie', 'Herding Group', array['border-collie', 'Border Collie', '보더콜리']::text[], true, 'akc', 194),
('beagle', '비글', 'Beagle', 'Hound Group', array['beagle', 'Beagle', '비글']::text[], true, 'akc', 50),
('bichon-frise', '비숑 프리제', 'Bichon Frise', 'Non-Sporting Group', array['bichon-frise', 'Bichon Frise', '비숑 프리제']::text[], true, 'akc', 165),
('samoyed', '사모예드', 'Samoyed', 'Working Group', array['samoyed', 'Samoyed', '사모예드']::text[], true, 'akc', 104),
('shiba-inu', '시바견', 'Shiba Inu', 'Non-Sporting Group', array['shiba-inu', 'Shiba Inu', '시바견']::text[], true, 'akc', 180),
('shih-tzu', '시츄', 'Shih Tzu', 'Toy Group', array['shih-tzu', 'Shih Tzu', '시츄']::text[], true, 'akc', 160),
('yorkshire-terrier', '요크셔테리어', 'Yorkshire Terrier', 'Toy Group', array['yorkshire-terrier', 'Yorkshire Terrier', '요크셔테리어']::text[], true, 'akc', 163),
('chihuahua', '치와와', 'Chihuahua', 'Toy Group', array['chihuahua', 'Chihuahua', '치와와']::text[], true, 'akc', 144),
('cardigan-welsh-corgi', '카디건 웰시코기', 'Cardigan Welsh Corgi', 'Herding Group', array['cardigan-welsh-corgi', 'Cardigan Welsh Corgi', '카디건 웰시코기']::text[], true, 'akc', 198),
('pembroke-welsh-corgi', '펨브로크 웰시코기', 'Pembroke Welsh Corgi', 'Herding Group', array['pembroke-welsh-corgi', 'Pembroke Welsh Corgi', '펨브로크 웰시코기']::text[], true, 'akc', 209),
('pomeranian', '포메라니안', 'Pomeranian', 'Toy Group', array['pomeranian', 'Pomeranian', '포메라니안']::text[], true, 'akc', 155),
('poodle', '푸들', 'Poodle', 'Toy Group, Non-Sporting Group', array['poodle', 'Poodle', '푸들']::text[], true, 'akc', 156),
('french-bulldog', '프렌치 불독', 'French Bulldog', 'Non-Sporting Group', array['french-bulldog', 'French Bulldog', '프렌치 불독']::text[], true, 'akc', 173),
('great-dane', '그레이트 데인', 'Great Dane', 'Working Group', array['great-dane', 'Great Dane', '그레이트 데인']::text[], false, 'akc', 1082),
('great-pyrenees', '그레이트 피레니즈', 'Great Pyrenees', 'Working Group', array['great-pyrenees', 'Great Pyrenees', '그레이트 피레니즈']::text[], false, 'akc', 1083),
('greyhound', '그레이하운드', 'Greyhound', 'Hound Group', array['greyhound', 'Greyhound', '그레이하운드']::text[], false, 'akc', 1049),
('other', '기타', 'Other', 'Other', array['other', '기타']::text[], false, 'meoksa', 9999),
('coton-de-tulear', '꼬똥 드 툴레아', 'Coton de Tulear', 'Non-Sporting Group', array['coton-de-tulear', 'Coton de Tulear', '꼬똥 드 툴레아']::text[], false, 'akc', 1160),
('neapolitan-mastiff', '나폴리탄 마스티프', 'Neapolitan Mastiff', 'Working Group', array['neapolitan-mastiff', 'Neapolitan Mastiff', '나폴리탄 마스티프']::text[], false, 'akc', 1089),
('norwegian-elkhound', '노르웨이 엘크하운드', 'Norwegian Elkhound', 'Hound Group', array['norwegian-elkhound', 'Norwegian Elkhound', '노르웨이 엘크하운드']::text[], false, 'akc', 1053),
('norwich-terrier', '노리치 테리어', 'Norwich Terrier', 'Terrier Group', array['norwich-terrier', 'Norwich Terrier', '노리치 테리어']::text[], false, 'akc', 1116),
('norfolk-terrier', '노퍽 테리어', 'Norfolk Terrier', 'Terrier Group', array['norfolk-terrier', 'Norfolk Terrier', '노퍽 테리어']::text[], false, 'akc', 1115),
('newfoundland', '뉴펀들랜드', 'Newfoundland', 'Working Group', array['newfoundland', 'Newfoundland', '뉴펀들랜드']::text[], false, 'akc', 1090),
('dalmatian', '달마시안', 'Dalmatian', 'Non-Sporting Group', array['dalmatian', 'Dalmatian', '달마시안']::text[], false, 'akc', 1161),
('dandie-dinmont-terrier', '댄디 딘몬트 테리어', 'Dandie Dinmont Terrier', 'Terrier Group', array['dandie-dinmont-terrier', 'Dandie Dinmont Terrier', '댄디 딘몬트 테리어']::text[], false, 'akc', 1107),
('dogue-de-bordeaux', '도그 드 보르도', 'Dogue de Bordeaux', 'Working Group', array['dogue-de-bordeaux', 'Dogue de Bordeaux', '도그 드 보르도']::text[], false, 'akc', 1079),
('doberman-pinscher', '도베르만 핀셔', 'Doberman Pinscher', 'Working Group', array['doberman-pinscher', 'Doberman Pinscher', '도베르만 핀셔']::text[], false, 'akc', 1077),
('lagotto-romagnolo', '라고토 로마뇰로', 'Lagotto Romagnolo', 'Sporting Group', array['lagotto-romagnolo', 'Lagotto Romagnolo', '라고토 로마뇰로']::text[], false, 'akc', 1022),
('lhasa-apso', '라사압소', 'Lhasa Apso', 'Non-Sporting Group', array['lhasa-apso', 'Lhasa Apso', '라사압소']::text[], false, 'akc', 1165),
('rat-terrier', '랫 테리어', 'Rat Terrier', 'Terrier Group', array['rat-terrier', 'Rat Terrier', '랫 테리어']::text[], false, 'akc', 1118),
('russell-terrier', '러셀 테리어', 'Russell Terrier', 'Terrier Group', array['russell-terrier', 'Russell Terrier', '러셀 테리어']::text[], false, 'akc', 1119),
('leonberger', '레온베르거', 'Leonberger', 'Working Group', array['leonberger', 'Leonberger', '레온베르거']::text[], false, 'akc', 1087),
('rhodesian-ridgeback', '로디지안 리지백', 'Rhodesian Ridgeback', 'Hound Group', array['rhodesian-ridgeback', 'Rhodesian Ridgeback', '로디지안 리지백']::text[], false, 'akc', 1060),
('lowchen', '로첸', 'Lowchen', 'Non-Sporting Group', array['lowchen', 'Lowchen', '로첸']::text[], false, 'akc', 1166),
('rottweiler', '로트와일러', 'Rottweiler', 'Working Group', array['rottweiler', 'Rottweiler', '로트와일러']::text[], false, 'akc', 1092),
('mastiff', '마스티프', 'Mastiff', 'Working Group', array['mastiff', 'Mastiff', '마스티프']::text[], false, 'akc', 1088),
('manchester-terrier', '맨체스터 테리어', 'Manchester Terrier', 'Terrier Group, Toy Group', array['manchester-terrier', 'Manchester Terrier', '맨체스터 테리어']::text[], false, 'akc', 1112),
('miniature-bull-terrier', '미니어처 불 테리어', 'Miniature Bull Terrier', 'Terrier Group', array['miniature-bull-terrier', 'Miniature Bull Terrier', '미니어처 불 테리어']::text[], false, 'akc', 1113),
('miniature-american-shepherd', '미니어처 아메리칸 셰퍼드', 'Miniature American Shepherd', 'Herding Group', array['miniature-american-shepherd', 'Miniature American Shepherd', '미니어처 아메리칸 셰퍼드']::text[], false, 'akc', 1195),
('miniature-pinscher', '미니어처 핀셔', 'Miniature Pinscher', 'Toy Group', array['miniature-pinscher', 'Miniature Pinscher', '미니어처 핀셔']::text[], false, 'akc', 1142),
('basenji', '바센지', 'Basenji', 'Hound Group', array['basenji', 'Basenji', '바센지']::text[], false, 'akc', 1037),
('basset-hound', '바셋 하운드', 'Basset Hound', 'Hound Group', array['basset-hound', 'Basset Hound', '바셋 하운드']::text[], false, 'akc', 1039),
('bernese-mountain-dog', '버니즈 마운틴 도그', 'Bernese Mountain Dog', 'Working Group', array['bernese-mountain-dog', 'Bernese Mountain Dog', '버니즈 마운틴 도그']::text[], false, 'akc', 1069),
('border-terrier', '보더 테리어', 'Border Terrier', 'Terrier Group', array['border-terrier', 'Border Terrier', '보더 테리어']::text[], false, 'akc', 1103),
('borzoi', '보르조이', 'Borzoi', 'Hound Group', array['borzoi', 'Borzoi', '보르조이']::text[], false, 'akc', 1044),
('boston-terrier', '보스턴 테리어', 'Boston Terrier', 'Non-Sporting Group', array['boston-terrier', 'Boston Terrier', '보스턴 테리어']::text[], false, 'akc', 1156),
('boxer', '복서', 'Boxer', 'Working Group', array['boxer', 'Boxer', '복서']::text[], false, 'akc', 1072),
('bull-terrier', '불 테리어', 'Bull Terrier', 'Terrier Group', array['bull-terrier', 'Bull Terrier', '불 테리어']::text[], false, 'akc', 1104),
('bulldog', '불도그', 'Bulldog', 'Non-Sporting Group', array['bulldog', 'Bulldog', '불도그']::text[], false, 'akc', 1157),
('bullmastiff', '불마스티프', 'Bullmastiff', 'Working Group', array['bullmastiff', 'Bullmastiff', '불마스티프']::text[], false, 'akc', 1073),
('brussels-griffon', '브뤼셀 그리펀', 'Brussels Griffon', 'Toy Group', array['brussels-griffon', 'Brussels Griffon', '브뤼셀 그리펀']::text[], false, 'akc', 1132),
('brittany', '브리타니', 'Brittany', 'Sporting Group', array['brittany', 'Brittany', '브리타니']::text[], false, 'akc', 1004),
('bloodhound', '블러드하운드', 'Bloodhound', 'Hound Group', array['bloodhound', 'Bloodhound', '블러드하운드']::text[], false, 'akc', 1042),
('bearded-collie', '비어디드 콜리', 'Bearded Collie', 'Herding Group', array['bearded-collie', 'Bearded Collie', '비어디드 콜리']::text[], false, 'akc', 1176),
('vizsla', '비즐라', 'Vizsla', 'Sporting Group', array['vizsla', 'Vizsla', '비즐라']::text[], false, 'akc', 1028),
('saluki', '살루키', 'Saluki', 'Hound Group', array['saluki', 'Saluki', '살루키']::text[], false, 'akc', 1061),
('st-bernard', '세인트 버나드', 'St. Bernard', 'Working Group', array['st-bernard', 'St. Bernard', '세인트 버나드']::text[], false, 'akc', 1093),
('shetland-sheepdog', '셰틀랜드 쉽독', 'Shetland Sheepdog', 'Herding Group', array['shetland-sheepdog', 'Shetland Sheepdog', '셰틀랜드 쉽독']::text[], false, 'akc', 1204),
('soft-coated-wheaten-terrier', '소프트 코티드 휘튼 테리어', 'Soft Coated Wheaten Terrier', 'Terrier Group', array['soft-coated-wheaten-terrier', 'Soft Coated Wheaten Terrier', '소프트 코티드 휘튼 테리어']::text[], false, 'akc', 1124),
('xoloitzcuintli', '솔로이츠퀸틀리', 'Xoloitzcuintli', 'Non-Sporting Group', array['xoloitzcuintli', 'Xoloitzcuintli', '솔로이츠퀸틀리']::text[], false, 'akc', 1173),
('scottish-terrier', '스코티시 테리어', 'Scottish Terrier', 'Terrier Group', array['scottish-terrier', 'Scottish Terrier', '스코티시 테리어']::text[], false, 'akc', 1120),
('schipperke', '스키퍼키', 'Schipperke', 'Non-Sporting Group', array['schipperke', 'Schipperke', '스키퍼키']::text[], false, 'akc', 1169),
('staffordshire-bull-terrier', '스태퍼드셔 불 테리어', 'Staffordshire Bull Terrier', 'Terrier Group', array['staffordshire-bull-terrier', 'Staffordshire Bull Terrier', '스태퍼드셔 불 테리어']::text[], false, 'akc', 1125),
('standard-schnauzer', '스탠더드 슈나우저', 'Standard Schnauzer', 'Working Group', array['standard-schnauzer', 'Standard Schnauzer', '스탠더드 슈나우저']::text[], false, 'akc', 1096),
('siberian-husky', '시베리안 허스키', 'Siberian Husky', 'Working Group', array['siberian-husky', 'Siberian Husky', '시베리안 허스키']::text[], false, 'akc', 1095),
('silky-terrier', '실키 테리어', 'Silky Terrier', 'Toy Group', array['silky-terrier', 'Silky Terrier', '실키 테리어']::text[], false, 'akc', 1151),
('american-staffordshire-terrier', '아메리칸 스태퍼드셔 테리어', 'American Staffordshire Terrier', 'Terrier Group', array['american-staffordshire-terrier', 'American Staffordshire Terrier', '아메리칸 스태퍼드셔 테리어']::text[], false, 'akc', 1100),
('american-eskimo-dog', '아메리칸 에스키모 도그', 'American Eskimo Dog', 'Non-Sporting Group', array['american-eskimo-dog', 'American Eskimo Dog', '아메리칸 에스키모 도그']::text[], false, 'akc', 1154),
('irish-setter', '아이리시 세터', 'Irish Setter', 'Sporting Group', array['irish-setter', 'Irish Setter', '아이리시 세터']::text[], false, 'akc', 1019),
('irish-wolfhound', '아이리시 울프하운드', 'Irish Wolfhound', 'Hound Group', array['irish-wolfhound', 'Irish Wolfhound', '아이리시 울프하운드']::text[], false, 'akc', 1052),
('akita', '아키타', 'Akita', 'Working Group', array['akita', 'Akita', '아키타']::text[], false, 'akc', 1066),
('affenpinscher', '아펜핀셔', 'Affenpinscher', 'Toy Group', array['affenpinscher', 'Affenpinscher', '아펜핀셔']::text[], false, 'akc', 1130),
('afghan-hound', '아프간 하운드', 'Afghan Hound', 'Hound Group', array['afghan-hound', 'Afghan Hound', '아프간 하운드']::text[], false, 'akc', 1033),
('alaskan-malamute', '알래스칸 말라뮤트', 'Alaskan Malamute', 'Working Group', array['alaskan-malamute', 'Alaskan Malamute', '알래스칸 말라뮤트']::text[], false, 'akc', 1067),
('airedale-terrier', '에어데일 테리어', 'Airedale Terrier', 'Terrier Group', array['airedale-terrier', 'Airedale Terrier', '에어데일 테리어']::text[], false, 'akc', 1098),
('australian-shepherd', '오스트레일리안 셰퍼드', 'Australian Shepherd', 'Herding Group', array['australian-shepherd', 'Australian Shepherd', '오스트레일리안 셰퍼드']::text[], false, 'akc', 1175),
('australian-cattle-dog', '오스트레일리안 캐틀 도그', 'Australian Cattle Dog', 'Herding Group', array['australian-cattle-dog', 'Australian Cattle Dog', '오스트레일리안 캐틀 도그']::text[], false, 'akc', 1174),
('australian-terrier', '오스트레일리안 테리어', 'Australian Terrier', 'Terrier Group', array['australian-terrier', 'Australian Terrier', '오스트레일리안 테리어']::text[], false, 'akc', 1101),
('old-english-sheepdog', '올드 잉글리시 쉽독', 'Old English Sheepdog', 'Herding Group', array['old-english-sheepdog', 'Old English Sheepdog', '올드 잉글리시 쉽독']::text[], false, 'akc', 1198),
('weimaraner', '와이마라너', 'Weimaraner', 'Sporting Group', array['weimaraner', 'Weimaraner', '와이마라너']::text[], false, 'akc', 1029),
('wire-fox-terrier', '와이어 폭스 테리어', 'Wire Fox Terrier', 'Terrier Group', array['wire-fox-terrier', 'Wire Fox Terrier', '와이어 폭스 테리어']::text[], false, 'akc', 1129),
('west-highland-white-terrier', '웨스트 하이랜드 화이트 테리어', 'West Highland White Terrier', 'Terrier Group', array['west-highland-white-terrier', 'West Highland White Terrier', '웨스트 하이랜드 화이트 테리어']::text[], false, 'akc', 1128),
('welsh-springer-spaniel', '웰시 스프링어 스패니얼', 'Welsh Springer Spaniel', 'Sporting Group', array['welsh-springer-spaniel', 'Welsh Springer Spaniel', '웰시 스프링어 스패니얼']::text[], false, 'akc', 1030),
('welsh-terrier', '웰시 테리어', 'Welsh Terrier', 'Terrier Group', array['welsh-terrier', 'Welsh Terrier', '웰시 테리어']::text[], false, 'akc', 1127),
('italian-greyhound', '이탈리안 그레이하운드', 'Italian Greyhound', 'Toy Group', array['italian-greyhound', 'Italian Greyhound', '이탈리안 그레이하운드']::text[], false, 'akc', 1138),
('english-setter', '잉글리시 세터', 'English Setter', 'Sporting Group', array['english-setter', 'English Setter', '잉글리시 세터']::text[], false, 'akc', 1010),
('english-springer-spaniel', '잉글리시 스프링어 스패니얼', 'English Springer Spaniel', 'Sporting Group', array['english-springer-spaniel', 'English Springer Spaniel', '잉글리시 스프링어 스패니얼']::text[], false, 'akc', 1011),
('english-cocker-spaniel', '잉글리시 코커 스패니얼', 'English Cocker Spaniel', 'Sporting Group', array['english-cocker-spaniel', 'English Cocker Spaniel', '잉글리시 코커 스패니얼']::text[], false, 'akc', 1009),
('english-toy-spaniel', '잉글리시 토이 스패니얼', 'English Toy Spaniel', 'Toy Group', array['english-toy-spaniel', 'English Toy Spaniel', '잉글리시 토이 스패니얼']::text[], false, 'akc', 1136),
('giant-schnauzer', '자이언트 슈나우저', 'Giant Schnauzer', 'Working Group', array['giant-schnauzer', 'Giant Schnauzer', '자이언트 슈나우저']::text[], false, 'akc', 1081),
('japanese-chin', '재패니즈 친', 'Japanese Chin', 'Toy Group', array['japanese-chin', 'Japanese Chin', '재패니즈 친']::text[], false, 'akc', 1139),
('german-shepherd-dog', '저먼 셰퍼드', 'German Shepherd Dog', 'Herding Group', array['german-shepherd-dog', 'German Shepherd Dog', '저먼 셰퍼드']::text[], false, 'akc', 1192),
('german-shorthaired-pointer', '저먼 쇼트헤어드 포인터', 'German Shorthaired Pointer', 'Sporting Group', array['german-shorthaired-pointer', 'German Shorthaired Pointer', '저먼 쇼트헤어드 포인터']::text[], false, 'akc', 1014),
('german-wirehaired-pointer', '저먼 와이어헤어드 포인터', 'German Wirehaired Pointer', 'Sporting Group', array['german-wirehaired-pointer', 'German Wirehaired Pointer', '저먼 와이어헤어드 포인터']::text[], false, 'akc', 1015),
('german-pinscher', '저먼 핀셔', 'German Pinscher', 'Working Group', array['german-pinscher', 'German Pinscher', '저먼 핀셔']::text[], false, 'akc', 1080),
('chow-chow', '차우차우', 'Chow Chow', 'Non-Sporting Group', array['chow-chow', 'Chow Chow', '차우차우']::text[], false, 'akc', 1159),
('chinese-shar-pei', '차이니즈 샤페이', 'Chinese Shar-Pei', 'Non-Sporting Group', array['chinese-shar-pei', 'Chinese Shar-Pei', '차이니즈 샤페이']::text[], false, 'akc', 1158),
('chinese-crested', '차이니즈 크레스티드', 'Chinese Crested', 'Toy Group', array['chinese-crested', 'Chinese Crested', '차이니즈 크레스티드']::text[], false, 'akc', 1135),
('chesapeake-bay-retriever', '체서피크 베이 리트리버', 'Chesapeake Bay Retriever', 'Sporting Group', array['chesapeake-bay-retriever', 'Chesapeake Bay Retriever', '체서피크 베이 리트리버']::text[], false, 'akc', 1005),
('canaan-dog', '카난 도그', 'Canaan Dog', 'Herding Group', array['canaan-dog', 'Canaan Dog', '카난 도그']::text[], false, 'akc', 1187),
('cane-corso', '카네 코르소', 'Cane Corso', 'Working Group', array['cane-corso', 'Cane Corso', '카네 코르소']::text[], false, 'akc', 1074),
('cavalier-king-charles-spaniel', '카발리에 킹 찰스 스패니얼', 'Cavalier King Charles Spaniel', 'Toy Group', array['cavalier-king-charles-spaniel', 'Cavalier King Charles Spaniel', '카발리에 킹 찰스 스패니얼']::text[], false, 'akc', 1133),
('kerry-blue-terrier', '케리 블루 테리어', 'Kerry Blue Terrier', 'Terrier Group', array['kerry-blue-terrier', 'Kerry Blue Terrier', '케리 블루 테리어']::text[], false, 'akc', 1110),
('cairn-terrier', '케언 테리어', 'Cairn Terrier', 'Terrier Group', array['cairn-terrier', 'Cairn Terrier', '케언 테리어']::text[], false, 'akc', 1105),
('komondor', '코몬도르', 'Komondor', 'Working Group', array['komondor', 'Komondor', '코몬도르']::text[], false, 'akc', 1085),
('cocker-spaniel', '코커 스패니얼', 'Cocker Spaniel', 'Sporting Group', array['cocker-spaniel', 'Cocker Spaniel', '코커 스패니얼']::text[], false, 'akc', 1007),
('collie', '콜리', 'Collie', 'Herding Group', array['collie', 'Collie', '콜리']::text[], false, 'akc', 1189),
('kuvasz', '쿠바스', 'Kuvasz', 'Working Group', array['kuvasz', 'Kuvasz', '쿠바스']::text[], false, 'akc', 1086),
('clumber-spaniel', '클럼버 스패니얼', 'Clumber Spaniel', 'Sporting Group', array['clumber-spaniel', 'Clumber Spaniel', '클럼버 스패니얼']::text[], false, 'akc', 1006),
('keeshond', '키스혼드', 'Keeshond', 'Non-Sporting Group', array['keeshond', 'Keeshond', '키스혼드']::text[], false, 'akc', 1164),
('toy-fox-terrier', '토이 폭스 테리어', 'Toy Fox Terrier', 'Toy Group', array['toy-fox-terrier', 'Toy Fox Terrier', '토이 폭스 테리어']::text[], false, 'akc', 1152),
('tibetan-mastiff', '티베탄 마스티프', 'Tibetan Mastiff', 'Working Group', array['tibetan-mastiff', 'Tibetan Mastiff', '티베탄 마스티프']::text[], false, 'akc', 1097),
('tibetan-spaniel', '티베탄 스패니얼', 'Tibetan Spaniel', 'Non-Sporting Group', array['tibetan-spaniel', 'Tibetan Spaniel', '티베탄 스패니얼']::text[], false, 'akc', 1171),
('tibetan-terrier', '티베탄 테리어', 'Tibetan Terrier', 'Non-Sporting Group', array['tibetan-terrier', 'Tibetan Terrier', '티베탄 테리어']::text[], false, 'akc', 1172),
('pharaoh-hound', '파라오 하운드', 'Pharaoh Hound', 'Hound Group', array['pharaoh-hound', 'Pharaoh Hound', '파라오 하운드']::text[], false, 'akc', 1056),
('papillon', '파피용', 'Papillon', 'Toy Group', array['papillon', 'Papillon', '파피용']::text[], false, 'akc', 1143),
('pug', '퍼그', 'Pug', 'Toy Group', array['pug', 'Pug', '퍼그']::text[], false, 'akc', 1147),
('pekingese', '페키니즈', 'Pekingese', 'Toy Group', array['pekingese', 'Pekingese', '페키니즈']::text[], false, 'akc', 1144),
('portuguese-water-dog', '포르투갈 워터 도그', 'Portuguese Water Dog', 'Working Group', array['portuguese-water-dog', 'Portuguese Water Dog', '포르투갈 워터 도그']::text[], false, 'akc', 1091),
('pointer', '포인터', 'Pointer', 'Sporting Group', array['pointer', 'Pointer', '포인터']::text[], false, 'akc', 1025),
('puli', '풀리', 'Puli', 'Herding Group', array['puli', 'Puli', '풀리']::text[], false, 'akc', 1201),
('flat-coated-retriever', '플랫 코티드 리트리버', 'Flat-Coated Retriever', 'Sporting Group', array['flat-coated-retriever', 'Flat-Coated Retriever', '플랫 코티드 리트리버']::text[], false, 'akc', 1013),
('finnish-lapphund', '핀란드 라프훈트', 'Finnish Lapphund', 'Herding Group', array['finnish-lapphund', 'Finnish Lapphund', '핀란드 라프훈트']::text[], false, 'akc', 1191),
('finnish-spitz', '핀란드 스피츠', 'Finnish Spitz', 'Non-Sporting Group', array['finnish-spitz', 'Finnish Spitz', '핀란드 스피츠']::text[], false, 'akc', 1162),
('havanese', '하바니즈', 'Havanese', 'Toy Group', array['havanese', 'Havanese', '하바니즈']::text[], false, 'akc', 1137),
('whippet', '휘핏', 'Whippet', 'Hound Group', array['whippet', 'Whippet', '휘핏']::text[], false, 'akc', 1065),
('american-english-coonhound', 'American English Coonhound', 'American English Coonhound', 'Hound Group', array['american-english-coonhound', 'American English Coonhound']::text[], false, 'akc', 1034),
('american-foxhound', 'American Foxhound', 'American Foxhound', 'Hound Group', array['american-foxhound', 'American Foxhound']::text[], false, 'akc', 1035),
('american-hairless-terrier', 'American Hairless Terrier', 'American Hairless Terrier', 'Terrier Group', array['american-hairless-terrier', 'American Hairless Terrier']::text[], false, 'akc', 1099),
('american-water-spaniel', 'American Water Spaniel', 'American Water Spaniel', 'Sporting Group', array['american-water-spaniel', 'American Water Spaniel']::text[], false, 'akc', 1000),
('anatolian-shepherd-dog', 'Anatolian Shepherd Dog', 'Anatolian Shepherd Dog', 'Working Group', array['anatolian-shepherd-dog', 'Anatolian Shepherd Dog']::text[], false, 'akc', 1068),
('azawakh', 'Azawakh', 'Azawakh', 'Hound Group', array['azawakh', 'Azawakh']::text[], false, 'akc', 1036),
('barbet', 'Barbet', 'Barbet', 'Sporting Group', array['barbet', 'Barbet']::text[], false, 'akc', 1001),
('basset-fauve-de-bretagne', 'Basset Fauve de Bretagne', 'Basset Fauve de Bretagne', 'Hound Group', array['basset-fauve-de-bretagne', 'Basset Fauve de Bretagne']::text[], false, 'akc', 1038),
('beauceron', 'Beauceron', 'Beauceron', 'Herding Group', array['beauceron', 'Beauceron']::text[], false, 'akc', 1177),
('bedlington-terrier', 'Bedlington Terrier', 'Bedlington Terrier', 'Terrier Group', array['bedlington-terrier', 'Bedlington Terrier']::text[], false, 'akc', 1102),
('belgian-laekenois', 'Belgian Laekenois', 'Belgian Laekenois', 'Herding Group', array['belgian-laekenois', 'Belgian Laekenois']::text[], false, 'akc', 1178),
('belgian-malinois', 'Belgian Malinois', 'Belgian Malinois', 'Herding Group', array['belgian-malinois', 'Belgian Malinois']::text[], false, 'akc', 1179),
('belgian-sheepdog', 'Belgian Sheepdog', 'Belgian Sheepdog', 'Herding Group', array['belgian-sheepdog', 'Belgian Sheepdog']::text[], false, 'akc', 1180),
('belgian-tervuren', 'Belgian Tervuren', 'Belgian Tervuren', 'Herding Group', array['belgian-tervuren', 'Belgian Tervuren']::text[], false, 'akc', 1181),
('bergamasco', 'Bergamasco', 'Bergamasco', 'Herding Group', array['bergamasco', 'Bergamasco']::text[], false, 'akc', 1182),
('berger-picard', 'Berger Picard', 'Berger Picard', 'Herding Group', array['berger-picard', 'Berger Picard']::text[], false, 'akc', 1183),
('biewer-terrier', 'Biewer Terrier', 'Biewer Terrier', 'Toy Group', array['biewer-terrier', 'Biewer Terrier']::text[], false, 'akc', 1131),
('black-and-tan-coonhound', 'Black and Tan Coonhound', 'Black and Tan Coonhound', 'Hound Group', array['black-and-tan-coonhound', 'Black and Tan Coonhound']::text[], false, 'akc', 1041),
('black-russian-terrier', 'Black Russian Terrier', 'Black Russian Terrier', 'Working Group', array['black-russian-terrier', 'Black Russian Terrier']::text[], false, 'akc', 1070),
('bluetick-coonhound', 'Bluetick Coonhound', 'Bluetick Coonhound', 'Hound Group', array['bluetick-coonhound', 'Bluetick Coonhound']::text[], false, 'akc', 1043),
('boerboel', 'Boerboel', 'Boerboel', 'Working Group', array['boerboel', 'Boerboel']::text[], false, 'akc', 1071),
('bouvier-des-flandres', 'Bouvier Des Flandres', 'Bouvier Des Flandres', 'Herding Group', array['bouvier-des-flandres', 'Bouvier Des Flandres']::text[], false, 'akc', 1185),
('boykin-spaniel', 'Boykin Spaniel', 'Boykin Spaniel', 'Sporting Group', array['boykin-spaniel', 'Boykin Spaniel']::text[], false, 'akc', 1002),
('bracco-italiano', 'Bracco Italiano', 'Bracco Italiano', 'Sporting Group', array['bracco-italiano', 'Bracco Italiano']::text[], false, 'akc', 1003),
('briard', 'Briard', 'Briard', 'Herding Group', array['briard', 'Briard']::text[], false, 'akc', 1186),
('cesky-terrier', 'Cesky Terrier', 'Cesky Terrier', 'Terrier Group', array['cesky-terrier', 'Cesky Terrier']::text[], false, 'akc', 1106),
('chinook', 'Chinook', 'Chinook', 'Working Group', array['chinook', 'Chinook']::text[], false, 'akc', 1075),
('cirneco-delletna', 'Cirneco dell''Etna', 'Cirneco dell''Etna', 'Hound Group', array['cirneco-delletna', 'Cirneco dell''Etna']::text[], false, 'akc', 1045),
('curly-coated-retriever', 'Curly-Coated Retriever', 'Curly-Coated Retriever', 'Sporting Group', array['curly-coated-retriever', 'Curly-Coated Retriever']::text[], false, 'akc', 1008),
('danish-swedish-farmdog', 'Danish-Swedish Farmdog', 'Danish-Swedish Farmdog', 'Working Group', array['danish-swedish-farmdog', 'Danish-Swedish Farmdog']::text[], false, 'akc', 1076),
('dogo-argentino', 'Dogo Argentino', 'Dogo Argentino', 'Working Group', array['dogo-argentino', 'Dogo Argentino']::text[], false, 'akc', 1078),
('english-foxhound', 'English Foxhound', 'English Foxhound', 'Hound Group', array['english-foxhound', 'English Foxhound']::text[], false, 'akc', 1047),
('entlebucher-mountain-dog', 'Entlebucher Mountain Dog', 'Entlebucher Mountain Dog', 'Herding Group', array['entlebucher-mountain-dog', 'Entlebucher Mountain Dog']::text[], false, 'akc', 1190),
('field-spaniel', 'Field Spaniel', 'Field Spaniel', 'Sporting Group', array['field-spaniel', 'Field Spaniel']::text[], false, 'akc', 1012),
('glen-of-imaal-terrier', 'Glen of Imaal Terrier', 'Glen of Imaal Terrier', 'Terrier Group', array['glen-of-imaal-terrier', 'Glen of Imaal Terrier']::text[], false, 'akc', 1108),
('gordon-setter', 'Gordon Setter', 'Gordon Setter', 'Sporting Group', array['gordon-setter', 'Gordon Setter']::text[], false, 'akc', 1017),
('grand-basset-griffon-vendeen', 'Grand Basset Griffon Vendeen', 'Grand Basset Griffon Vendeen', 'Hound Group', array['grand-basset-griffon-vendeen', 'Grand Basset Griffon Vendeen']::text[], false, 'akc', 1048),
('greater-swiss-mountain-dog', 'Greater Swiss Mountain Dog', 'Greater Swiss Mountain Dog', 'Working Group', array['greater-swiss-mountain-dog', 'Greater Swiss Mountain Dog']::text[], false, 'akc', 1084),
('harrier', 'Harrier', 'Harrier', 'Hound Group', array['harrier', 'Harrier']::text[], false, 'akc', 1050),
('ibizan-hound', 'Ibizan Hound', 'Ibizan Hound', 'Hound Group', array['ibizan-hound', 'Ibizan Hound']::text[], false, 'akc', 1051),
('icelandic-sheepdog', 'Icelandic Sheepdog', 'Icelandic Sheepdog', 'Herding Group', array['icelandic-sheepdog', 'Icelandic Sheepdog']::text[], false, 'akc', 1193),
('irish-red-and-white-setter', 'Irish Red and White Setter', 'Irish Red and White Setter', 'Sporting Group', array['irish-red-and-white-setter', 'Irish Red and White Setter']::text[], false, 'akc', 1018),
('irish-terrier', 'Irish Terrier', 'Irish Terrier', 'Terrier Group', array['irish-terrier', 'Irish Terrier']::text[], false, 'akc', 1109),
('irish-water-spaniel', 'Irish Water Spaniel', 'Irish Water Spaniel', 'Sporting Group', array['irish-water-spaniel', 'Irish Water Spaniel']::text[], false, 'akc', 1020),
('lakeland-terrier', 'Lakeland Terrier', 'Lakeland Terrier', 'Terrier Group', array['lakeland-terrier', 'Lakeland Terrier']::text[], false, 'akc', 1111),
('lancashire-heeler', 'Lancashire Heeler', 'Lancashire Heeler', 'Herding Group', array['lancashire-heeler', 'Lancashire Heeler']::text[], false, 'akc', 1194),
('mudi', 'Mudi', 'Mudi', 'Herding Group', array['mudi', 'Mudi']::text[], false, 'akc', 1196),
('nederlandse-kooikerhondje', 'Nederlandse Kooikerhondje', 'Nederlandse Kooikerhondje', 'Sporting Group', array['nederlandse-kooikerhondje', 'Nederlandse Kooikerhondje']::text[], false, 'akc', 1023),
('norwegian-buhund', 'Norwegian Buhund', 'Norwegian Buhund', 'Herding Group', array['norwegian-buhund', 'Norwegian Buhund']::text[], false, 'akc', 1197),
('norwegian-lundehund', 'Norwegian Lundehund', 'Norwegian Lundehund', 'Non-Sporting Group', array['norwegian-lundehund', 'Norwegian Lundehund']::text[], false, 'akc', 1167),
('nova-scotia-duck-tolling-retriever', 'Nova Scotia Duck Tolling Retriever', 'Nova Scotia Duck Tolling Retriever', 'Sporting Group', array['nova-scotia-duck-tolling-retriever', 'Nova Scotia Duck Tolling Retriever']::text[], false, 'akc', 1024),
('otterhound', 'Otterhound', 'Otterhound', 'Hound Group', array['otterhound', 'Otterhound']::text[], false, 'akc', 1054),
('parson-russell-terrier', 'Parson Russell Terrier', 'Parson Russell Terrier', 'Terrier Group', array['parson-russell-terrier', 'Parson Russell Terrier']::text[], false, 'akc', 1117),
('petit-basset-griffon-vendeen', 'Petit Basset Griffon Vendeen', 'Petit Basset Griffon Vendeen', 'Hound Group', array['petit-basset-griffon-vendeen', 'Petit Basset Griffon Vendeen']::text[], false, 'akc', 1055),
('plott-hound', 'Plott Hound', 'Plott Hound', 'Hound Group', array['plott-hound', 'Plott Hound']::text[], false, 'akc', 1057),
('polish-lowland-sheepdog', 'Polish Lowland Sheepdog', 'Polish Lowland Sheepdog', 'Herding Group', array['polish-lowland-sheepdog', 'Polish Lowland Sheepdog']::text[], false, 'akc', 1200),
('portuguese-podengo-pequeno', 'Portuguese Podengo Pequeno', 'Portuguese Podengo Pequeno', 'Hound Group', array['portuguese-podengo-pequeno', 'Portuguese Podengo Pequeno']::text[], false, 'akc', 1058),
('pumi', 'Pumi', 'Pumi', 'Herding Group', array['pumi', 'Pumi']::text[], false, 'akc', 1202),
('pyrenean-shepherd', 'Pyrenean Shepherd', 'Pyrenean Shepherd', 'Herding Group', array['pyrenean-shepherd', 'Pyrenean Shepherd']::text[], false, 'akc', 1203),
('redbone-coonhound', 'Redbone Coonhound', 'Redbone Coonhound', 'Hound Group', array['redbone-coonhound', 'Redbone Coonhound']::text[], false, 'akc', 1059),
('russian-toy', 'Russian Toy', 'Russian Toy', 'Toy Group', array['russian-toy', 'Russian Toy']::text[], false, 'akc', 1148),
('russian-tsvetnaya-bolonka', 'Russian Tsvetnaya Bolonka', 'Russian Tsvetnaya Bolonka', 'Toy Group', array['russian-tsvetnaya-bolonka', 'Russian Tsvetnaya Bolonka']::text[], false, 'akc', 1149),
('scottish-deerhound', 'Scottish Deerhound', 'Scottish Deerhound', 'Hound Group', array['scottish-deerhound', 'Scottish Deerhound']::text[], false, 'akc', 1062),
('sealyham-terrier', 'Sealyham Terrier', 'Sealyham Terrier', 'Terrier Group', array['sealyham-terrier', 'Sealyham Terrier']::text[], false, 'akc', 1121),
('skye-terrier', 'Skye Terrier', 'Skye Terrier', 'Terrier Group', array['skye-terrier', 'Skye Terrier']::text[], false, 'akc', 1122),
('sloughi', 'Sloughi', 'Sloughi', 'Hound Group', array['sloughi', 'Sloughi']::text[], false, 'akc', 1063),
('smooth-fox-terrier', 'Smooth Fox Terrier', 'Smooth Fox Terrier', 'Terrier Group', array['smooth-fox-terrier', 'Smooth Fox Terrier']::text[], false, 'akc', 1123),
('spanish-water-dog', 'Spanish Water Dog', 'Spanish Water Dog', 'Herding Group', array['spanish-water-dog', 'Spanish Water Dog']::text[], false, 'akc', 1205),
('spinone-italiano', 'Spinone Italiano', 'Spinone Italiano', 'Sporting Group', array['spinone-italiano', 'Spinone Italiano']::text[], false, 'akc', 1026),
('sussex-spaniel', 'Sussex Spaniel', 'Sussex Spaniel', 'Sporting Group', array['sussex-spaniel', 'Sussex Spaniel']::text[], false, 'akc', 1027),
('swedish-vallhund', 'Swedish Vallhund', 'Swedish Vallhund', 'Herding Group', array['swedish-vallhund', 'Swedish Vallhund']::text[], false, 'akc', 1206),
('teddy-roosevelt-terrier', 'Teddy Roosevelt Terrier', 'Teddy Roosevelt Terrier', 'Terrier Group', array['teddy-roosevelt-terrier', 'Teddy Roosevelt Terrier']::text[], false, 'akc', 1126),
('treeing-walker-coonhound', 'Treeing Walker Coonhound', 'Treeing Walker Coonhound', 'Hound Group', array['treeing-walker-coonhound', 'Treeing Walker Coonhound']::text[], false, 'akc', 1064),
('wirehaired-pointing-griffon', 'Wirehaired Pointing Griffon', 'Wirehaired Pointing Griffon', 'Sporting Group', array['wirehaired-pointing-griffon', 'Wirehaired Pointing Griffon']::text[], false, 'akc', 1031),
('wirehaired-vizsla', 'Wirehaired Vizsla', 'Wirehaired Vizsla', 'Sporting Group', array['wirehaired-vizsla', 'Wirehaired Vizsla']::text[], false, 'akc', 1032)
on conflict (id) do update set
  name_ko = excluded.name_ko,
  name_en = excluded.name_en,
  group_name = excluded.group_name,
  aliases = excluded.aliases,
  is_popular = excluded.is_popular,
  source = excluded.source,
  sort_order = excluded.sort_order,
  updated_at = now();
